/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

public class ASRRequestBodyData {

    @SerializedName("config")
    private RecognitionConfig config = null;
    @SerializedName("audio")
    private RecognitionAudioData audio = null;

    public ASRRequestBodyData(RecognitionConfig config, RecognitionAudioData audio) {
        this.config = config;
        this.audio = audio;
    }

    /**
     *
     **/
    public RecognitionConfig getConfig() {
        return config;
    }

    public void setConfig(RecognitionConfig config) {
        this.config = config;
    }

    /**
     *
     **/
    public RecognitionAudioData getAudio() {
        return audio;
    }

    public void setAudio(RecognitionAudioData audio) {
        this.audio = audio;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ASRRequestBodyData aSRRequestBodyData = (ASRRequestBodyData) o;
        return (this.config == null ? aSRRequestBodyData.config == null : this.config.equals(aSRRequestBodyData.config)) &&
                (this.audio == null ? aSRRequestBodyData.audio == null : this.audio.equals(aSRRequestBodyData.audio));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.config == null ? 0 : this.config.hashCode());
        result = 31 * result + (this.audio == null ? 0 : this.audio.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ASRRequestBodyData {\n");

        sb.append("  config: ").append(config).append("\n");
        sb.append("  audio: ").append(audio).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
