/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

public class ErrorResponseBody {

    @SerializedName("status")
    private int status = 0;
    @SerializedName("detail")
    private String detail = null;
    @SerializedName("title")
    private String title = null;
    @SerializedName("type")
    private String type = null;

    public ErrorResponseBody(int status, String detail, String title, String type) {
        this.status = status;
        this.detail = detail;
        this.title = title;
        this.type = type;
    }

    /**
     * HTTP response status code.
     **/
    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Message explaining the issue.
     **/
    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * ErrorResponseBody message title.
     **/
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * ErrorResponseBody type.
     **/
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ErrorResponseBody error = (ErrorResponseBody) o;
        return (this.status == 0 ? error.status == 0 : this.status == error.status) &&
                (this.detail == null ? error.detail == null : this.detail.equals(error.detail)) &&
                (this.title == null ? error.title == null : this.title.equals(error.title)) &&
                (this.type == null ? error.type == null : this.type.equals(error.type));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.status);
        result = 31 * result + (this.detail == null ? 0 : this.detail.hashCode());
        result = 31 * result + (this.title == null ? 0 : this.title.hashCode());
        result = 31 * result + (this.type == null ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ErrorResponseBody {\n");

        sb.append("  status: ").append(status).append("\n");
        sb.append("  detail: ").append(detail).append("\n");
        sb.append("  title: ").append(title).append("\n");
        sb.append("  type: ").append(type).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
