/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

import farsava.core.Util.Enums;

public class HealthCheckResponseBody {

    @SerializedName("status")
    private Enums.Status status = null;
    @SerializedName("message")
    private String message = null;
    @SerializedName("version")
    private String version = null;

    public HealthCheckResponseBody(Enums.Status status, String message, String version) {
        this.status = status;
        this.message = message;
        this.version = version;
    }

    /**
     *
     **/
    public String getStatus() {
        return status.name();
    }

    public void setStatus(Enums.Status status) {
        this.status = status;
    }

    /**
     * Health check message. Returns *OK* if running without problem.
     **/
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * API version.
     **/
    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
