/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

/**
 * The Synthesizer requires either plain text or SSML as input. Only provide text OR ssml. Providing both will result in a bad request response.
 **/
public class SynthesisInput {

    @SerializedName("text")
    private String text = null;
    @SerializedName("ssml")
    private String ssml = null;

    public SynthesisInput(String text) {
        this.text = text;
    }

    /**
     * The raw text to be synthesized.
     **/
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    /**
     * The SSML document to be synthesized. The SSML document must be valid and well-formed.
     **/
    public String getSsml() {
        return ssml;
    }

    public void setSsml(String ssml) {
        this.ssml = ssml;
    }
}
