/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

import farsava.core.Util.Enums;

/**
 * The configuration of the synthesized audio.
 **/

public class TTSAudioConfig {

    @SerializedName("audioEncoding")
    private Enums.AudioEncoding audioEncoding;
    @SerializedName("sampleRateHertz")
    private Integer sampleRateHertz = 16000;
    @SerializedName("speakingRate")
    private float speakingRate = 1.0f;
    @SerializedName("pitch")
    private float pitch = 0.0f;
    @SerializedName("volumeGainDb")
    private float volumeGainDb = 0.0f;

    public TTSAudioConfig(Enums.AudioEncoding audioEncoding, Integer sampleRateHertz) {
        this.audioEncoding = audioEncoding;
        this.sampleRateHertz = sampleRateHertz;
    }

    /**
     *
     **/
    public String getAudioEncoding() {
        return audioEncoding.name();
    }

    public void setAudioEncoding(Enums.AudioEncoding audioEncoding) {
        this.audioEncoding = audioEncoding;
    }

    /**
     * Sample rate in Hertz of the audio data sent in all RecognitionAudio messages. Valid values are 8000-48000. 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that is not possible, use the native sample rate of the audio source (instead of re-sampling). This field is required for all audio formats. In Text to Speech endpoint is the synthesis sample rate (in hertz) for audio and Optional. If this is different from the voice's natural sample rate, then the synthesizer will honor this request by converting to the desired sample rate (which might result in worse audio quality), unless the specified sample rate is not supported for the encoding chosen.
     **/
    public Integer getSampleRateHertz() {
        return sampleRateHertz;
    }

    public void setSampleRateHertz(Integer sampleRateHertz) {
        this.sampleRateHertz = sampleRateHertz;
    }

    /**
     * Optional speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error.
     * minimum: 0.25
     * maximum: 4
     **/
    public float getSpeakingRate() {
        return speakingRate;
    }

    public void setSpeakingRate(float speakingRate) {
        this.speakingRate = speakingRate;
    }

    /**
     * Optional speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch.
     * minimum: -20.0
     * maximum: 20.0
     **/
    public float getPitch() {
        return pitch;
    }

    public void setPitch(float pitch) {
        this.pitch = pitch;
    }

    /**
     * Optional volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB) will play at approximately half the amplitude of the normal native signal amplitude. A value of +6.0 (dB) will play at approximately twice the amplitude of the normal native signal amplitude. Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that.
     * minimum: -96.0
     * maximum: 16.0
     **/
    public float getVolumeGainDb() {
        return volumeGainDb;
    }

    public void setVolumeGainDb(float volumeGainDb) {
        this.volumeGainDb = volumeGainDb;
    }
}
