/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.Model;

import com.google.gson.annotations.SerializedName;

public class TTSRequestBody {

    @SerializedName("synthesisInput")
    private SynthesisInput synthesisInput = null;
    @SerializedName("voiceConfig")
    private VoiceSelectionParams voiceConfig = null;
    @SerializedName("audioConfig")
    private TTSAudioConfig audioConfig = null;

    /**
     *
     **/
    public SynthesisInput getSynthesisInput() {
        return synthesisInput;
    }

    public void setSynthesisInput(SynthesisInput synthesisInput) {
        this.synthesisInput = synthesisInput;
    }

    /**
     *
     **/
    public VoiceSelectionParams getVoiceConfig() {
        return voiceConfig;
    }

    public void setVoiceConfig(VoiceSelectionParams voiceConfig) {
        this.voiceConfig = voiceConfig;
    }

    /**
     *
     **/
    public TTSAudioConfig getAudioConfig() {
        return audioConfig;
    }

    public void setAudioConfig(TTSAudioConfig audioConfig) {
        this.audioConfig = audioConfig;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TTSRequestBody tTSRequestBody = (TTSRequestBody) o;
        return (this.synthesisInput == null ? tTSRequestBody.synthesisInput == null : this.synthesisInput.equals(tTSRequestBody.synthesisInput)) &&
                (this.voiceConfig == null ? tTSRequestBody.voiceConfig == null : this.voiceConfig.equals(tTSRequestBody.voiceConfig)) &&
                (this.audioConfig == null ? tTSRequestBody.audioConfig == null : this.audioConfig.equals(tTSRequestBody.audioConfig));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.synthesisInput == null ? 0 : this.synthesisInput.hashCode());
        result = 31 * result + (this.voiceConfig == null ? 0 : this.voiceConfig.hashCode());
        result = 31 * result + (this.audioConfig == null ? 0 : this.audioConfig.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TTSRequestBody {\n");

        sb.append("  synthesisInput: ").append(synthesisInput).append("\n");
        sb.append("  voiceConfig: ").append(voiceConfig).append("\n");
        sb.append("  audioConfig: ").append(audioConfig).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
