/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.amerandish.farsava.core.Model;

import com.amerandish.farsava.core.Util.Enums;
import com.google.gson.annotations.SerializedName;

public class HealthCheckResponseBody {

    @SerializedName("status")
    private Enums.Status status = null;
    @SerializedName("message")
    private String message = null;
    @SerializedName("version")
    private String version = null;

    public HealthCheckResponseBody(Enums.Status status, String message, String version) {
        this.status = status;
        this.message = message;
        this.version = version;
    }

    /**
     *
     **/
    public String getStatus() {
        return status.name();
    }

    public void setStatus(Enums.Status status) {
        this.status = status;
    }

    /**
     * Health check message. Returns *OK* if running without problem.
     **/
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * API version.
     **/
    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HealthCheckResponseBody healthCheckResponseBody = (HealthCheckResponseBody) o;
        return (this.status == null ? healthCheckResponseBody.status == null : this.status.equals(healthCheckResponseBody.status)) &&
                (this.message == null ? healthCheckResponseBody.message == null : this.message.equals(healthCheckResponseBody.message)) &&
                (this.version == null ? healthCheckResponseBody.version == null : this.version.equals(healthCheckResponseBody.version));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.status == null ? 0 : this.status.hashCode());
        result = 31 * result + (this.message == null ? 0 : this.message.hashCode());
        result = 31 * result + (this.version == null ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class HealthCheckResponseBody {\n");

        sb.append("  status: ").append(status).append("\n");
        sb.append("  message: ").append(message).append("\n");
        sb.append("  version: ").append(version).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
