/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.amerandish.farsava.core.Model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

public class LanguageModelTrainRequestBody {

    @SerializedName("corpora")
    private List<String> corpora = null;
    @SerializedName("name")
    private String name = null;

    /**
     * An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.
     **/
    public List<String> getCorpora() {
        return corpora;
    }

    public void setCorpora(List<String> corpora) {
        this.corpora = corpora;
    }

    /**
     * The name of the custom language model being created.
     **/
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LanguageModelTrainRequestBody languageModelTrainRequestBody = (LanguageModelTrainRequestBody) o;
        return (this.corpora == null ? languageModelTrainRequestBody.corpora == null : this.corpora.equals(languageModelTrainRequestBody.corpora)) &&
                (this.name == null ? languageModelTrainRequestBody.name == null : this.name.equals(languageModelTrainRequestBody.name));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.corpora == null ? 0 : this.corpora.hashCode());
        result = 31 * result + (this.name == null ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LanguageModelTrainRequestBody {\n");

        sb.append("  corpora: ").append(corpora).append("\n");
        sb.append("  name: ").append(name).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
