/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.amerandish.farsava.core.Model;

import com.google.gson.annotations.SerializedName;

/**
 * Contains audio data in the encoding specified in the RecognitionConfig.    A base64-encoded string.   *For asr endpoint only binary data is accepted.*      Property | Description   ------------ | -------------   data | The audio data bytes encoded as specified in RecognitionConfig. A base64-encoded string.
 **/
public class RecognitionAudioData {

    @SerializedName("data")
    private byte[] data = null;

    /**
     * The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string.
     **/
    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RecognitionAudioData recognitionAudioData = (RecognitionAudioData) o;
        return (this.data == null ? recognitionAudioData.data == null : this.data.equals(recognitionAudioData.data));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.data == null ? 0 : this.data.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RecognitionAudioData {\n");

        sb.append("  data: ").append(data).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
