/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.amerandish.farsava.core.Model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

public class SpeechRecognitionResult {

    @SerializedName("transcript")
    private String transcript = null;
    @SerializedName("confidence")
    private Double confidence = null;
    @SerializedName("words")
    private List<WordInfo> words = null;

    /**
     * A UTF8-Encoded string. Transcript text representing the words that the user spoke.
     **/
    public String getTranscript() {
        return transcript;
    }

    public void setTranscript(String transcript) {
        this.transcript = transcript;
    }

    /**
     * The confidence of ASR engine for generated output. The confidence estimate between 0.0 and 1.0. A higher number indicates an estimated greater likelihood that the recognized words are correct. It is the total confidence of recognition in transcript level and each word confidence in word info object. This field is not guaranteed to be accurate and users should not rely on it to be always provided. The default of 0.0 is a sentinel value indicating confidence was not set.
     * minimum: 0
     * maximum: 1
     **/
    public Double getConfidence() {
        return confidence;
    }

    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    /**
     *
     **/
    public List<WordInfo> getWords() {
        return words;
    }

    public void setWords(List<WordInfo> words) {
        this.words = words;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SpeechRecognitionResult speechRecognitionResult = (SpeechRecognitionResult) o;
        return (this.transcript == null ? speechRecognitionResult.transcript == null : this.transcript.equals(speechRecognitionResult.transcript)) &&
                (this.confidence == null ? speechRecognitionResult.confidence == null : this.confidence.equals(speechRecognitionResult.confidence)) &&
                (this.words == null ? speechRecognitionResult.words == null : this.words.equals(speechRecognitionResult.words));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.transcript == null ? 0 : this.transcript.hashCode());
        result = 31 * result + (this.confidence == null ? 0 : this.confidence.hashCode());
        result = 31 * result + (this.words == null ? 0 : this.words.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SpeechRecognitionResult {\n");

        sb.append("  transcript: ").append(transcript).append("\n");
        sb.append("  confidence: ").append(confidence).append("\n");
        sb.append("  words: ").append(words).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
