/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.amerandish.farsava.core.Model;

import com.amerandish.farsava.core.Util.Enums;
import com.google.gson.annotations.SerializedName;

import java.util.UUID;

/**
 * The desired voice of the synthesized audio.
 **/
public class VoiceSelectionParams {

    @SerializedName("voiceId")
    private UUID voiceId = null;
    @SerializedName("languageCode")
    private Enums.LanguageCode languageCode = null;
    @SerializedName("name")
    private String name = null;
    @SerializedName("gender")
    private Enums.VoiceGender gender = null;

    /**
     * id of the desired voice to synthesize.
     **/
    public UUID getVoiceId() {
        return voiceId;
    }

    public void setVoiceId(UUID voiceId) {
        this.voiceId = voiceId;
    }

    /**
     *
     **/
    public String getLanguageCode() {
        return languageCode.name();
    }

    public void setLanguageCode(Enums.LanguageCode languageCode) {
        this.languageCode = languageCode;
    }

    /**
     * Name of the desired voice.
     **/
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     **/
    public String getGender() {
        return gender.name();
    }

    public void setGender(Enums.VoiceGender gender) {
        this.gender = gender;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VoiceSelectionParams voiceSelectionParams = (VoiceSelectionParams) o;
        return (this.voiceId == null ? voiceSelectionParams.voiceId == null : this.voiceId.equals(voiceSelectionParams.voiceId)) &&
                (this.languageCode == null ? voiceSelectionParams.languageCode == null : this.languageCode.equals(voiceSelectionParams.languageCode)) &&
                (this.name == null ? voiceSelectionParams.name == null : this.name.equals(voiceSelectionParams.name)) &&
                (this.gender == null ? voiceSelectionParams.gender == null : this.gender.equals(voiceSelectionParams.gender));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.voiceId == null ? 0 : this.voiceId.hashCode());
        result = 31 * result + (this.languageCode == null ? 0 : this.languageCode.hashCode());
        result = 31 * result + (this.name == null ? 0 : this.name.hashCode());
        result = 31 * result + (this.gender == null ? 0 : this.gender.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VoiceSelectionParams {\n");

        sb.append("  voiceId: ").append(voiceId).append("\n");
        sb.append("  languageCode: ").append(languageCode).append("\n");
        sb.append("  name: ").append(name).append("\n");
        sb.append("  gender: ").append(gender).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
