/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.data.model;

import com.google.gson.annotations.SerializedName;

public class ASRRequestBodyURI {

    @SerializedName("config")
    private RecognitionConfig config = null;
    @SerializedName("audio")
    private RecognitionAudioURI audio = null;

    /**
     *
     **/
    public RecognitionConfig getConfig() {
        return config;
    }

    public void setConfig(RecognitionConfig config) {
        this.config = config;
    }

    /**
     *
     **/
    public RecognitionAudioURI getAudio() {
        return audio;
    }

    public void setAudio(RecognitionAudioURI audio) {
        this.audio = audio;
    }
}
