/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.data.model;

import com.google.gson.annotations.SerializedName;

public class ErrorResponseBody {

    @SerializedName("status")
    private int status = 0;
    @SerializedName("detail")
    private String detail = null;
    @SerializedName("title")
    private String title = null;
    @SerializedName("type")
    private String type = null;

    public ErrorResponseBody(int status, String detail, String title, String type) {
        this.status = status;
        this.detail = detail;
        this.title = title;
        this.type = type;
    }

    /**
     * HTTP response status code.
     **/
    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Message explaining the issue.
     **/
    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * ErrorResponseBody message title.
     **/
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * ErrorResponseBody type.
     **/
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
