/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.data.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

public class LanguageModelTrainRequestBody {

    @SerializedName("corpora")
    private List<String> corpora = null;
    @SerializedName("name")
    private String name = null;

    /**
     * An array of text data to train a custom model. This text data can be keywords/phrases, or historical transcripts (transcriptionId of previous speechRecognitionResult). All values in the array must be a string.
     **/
    public List<String> getCorpora() {
        return corpora;
    }

    public void setCorpora(List<String> corpora) {
        this.corpora = corpora;
    }

    /**
     * The name of the custom language model being created.
     **/
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
