/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.data.model;

import com.google.gson.annotations.SerializedName;

/**
 * Contains audio data in the encoding specified in the RecognitionConfig.    A base64-encoded string.   *For asr endpoint only binary data is accepted.*      Property | Description   ------------ | -------------   data | The audio data bytes encoded as specified in RecognitionConfig. A base64-encoded string.
 **/
public class RecognitionAudioData {

    @SerializedName("data")
    private String data = null;

    public RecognitionAudioData(String data) {
        this.data = data;
    }

    /**
     * The audio data bytes encoded as specified in RecognitionConfig.   A base64-encoded string.
     **/
    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}
