/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 * <p>
 * OpenAPI spec version: 1.0.6
 * Contact: amir@amerandish.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package farsava.core.data.model;

import com.google.gson.annotations.SerializedName;

public class TTSRequestBody {

    @SerializedName("synthesisInput")
    private SynthesisInput synthesisInput;
    @SerializedName("voiceConfig")
    private VoiceSelectionParams voiceConfig;
    @SerializedName("audioConfig")
    private TTSAudioConfig audioConfig;

    public TTSRequestBody(SynthesisInput synthesisInput, VoiceSelectionParams voiceConfig, TTSAudioConfig audioConfig) {
        this.synthesisInput = synthesisInput;
        this.voiceConfig = voiceConfig;
        this.audioConfig = audioConfig;
    }


    /**
     *
     **/
    public SynthesisInput getSynthesisInput() {
        return synthesisInput;
    }

    public void setSynthesisInput(SynthesisInput synthesisInput) {
        this.synthesisInput = synthesisInput;
    }

    /**
     *
     **/
    public VoiceSelectionParams getVoiceConfig() {
        return voiceConfig;
    }

    public void setVoiceConfig(VoiceSelectionParams voiceConfig) {
        this.voiceConfig = voiceConfig;
    }

    /**
     *
     **/
    public TTSAudioConfig getAudioConfig() {
        return audioConfig;
    }

    public void setAudioConfig(TTSAudioConfig audioConfig) {
        this.audioConfig = audioConfig;
    }
}
